services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: rccma
      POSTGRES_PASSWORD: rccma
      POSTGRES_DB: rccma
    ports:
      - "5432:5432"
    volumes:
      - rccma_pg:/var/lib/postgresql/data
volumes:
  rccma_pg:
